---
- name: Download Oracle JDK 8
  get_url: url=https://secure.chakree.me/tmp/agile/jdk-8u151-linux-x64.rpm dest=/tmp/jdk-8u151-linux-x64.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install Oracle JDK 8
  command: yum -y install /tmp/jdk-8u151-linux-x64.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  ignore_errors: yes

- name: Install Tomcat 8 dependency
  yum: name=haveged state=present

- name: Start Tomcat
  service: name=haveged state=started enabled=yes

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=https://secure.chakree.me/tmp/agile/apache-tomcat-8.5.24.tar.gz dest=/tmp/apache-tomcat-8.5.24.tar.gz

- name: Extract archive
  command: chdir=/usr/share /usr/bin/tar xvf /tmp/apache-tomcat-8.5.24.tar.gz -C /opt/ creates=/opt/apache-tomcat

- name: Move Tomcat Folder
  command: chdir=/opt mv apache-tomcat-8.5.24 apache-tomcat

# - name: Symlink install directory
#   file: src=/opt/apache-tomcat path=/usr/share/tomcat state=link

- name: Change ownership of Tomcat installation
  file: path=/opt/apache-tomcat owner=tomcat group=tomcat state=directory recurse=yes

- name: Install Tomcat User configuration
  copy: src=tomcat-users.xml dest=/opt/apache-tomcat/conf/tomcat-users.xml mode=0755

- name: Install Tomcat Manager configuration
  copy: src=context.xml dest=/opt/apache-tomcat/webapps/manager/META-INF/context.xml mode=0755

- name: Install Tomcat Host Manager configuration
  copy: src=context.xml dest=/opt/apache-tomcat/webapps/host-manager/META-INF/context.xml mode=0755

# - name: Configure Tomcat server
#   template: src=server.xml dest=/usr/share/tomcat/conf/
#   notify: restart tomcat

# - name: Configure Tomcat users
#   template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
#   notify: restart tomcat

- name: Install Tomcat init script
  copy: src=tomcat.service dest=/etc/systemd/system/tomcat.service mode=0755

- name: Restart systemd
  command: systemctl daemon-reload

- name: Start Tomcat
  service: name=tomcat state=started enabled=yes

- name: deploy iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
  notify: restart iptables

- name: insert firewalld rule for tomcat http port
  firewalld: port=8080/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: insert firewalld rule for tomcat https port
  firewalld: port=8443/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: wait for tomcat to start
  wait_for: port=8080