---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: insert firewalld rule
  firewalld: port=3306/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

# - name: Disallow root login remotely
#   command: 'mysql -ne "{{ item }}"'
#   with_items:
#     - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
#   changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True


- name: Set root localhost Password
  mysql_user: name=root host={{ item }} password=sitagile 
              check_implicit_admin=yes
              login_user="root"
              login_password=""
              state=present
  with_items:
    - localhost

- name: Set root 127.0.0.1 Password
  mysql_user: name=root host={{ item }} password=sitagile 
              check_implicit_admin=yes
              login_user="root"
              login_password="sitagile"
              state=present
  with_items:
    - 127.0.0.1
    - ::1


- name: Add Root Remote Login User
  mysql_user:
    name: root
    password: sitagile
    host: '%'
    priv: '*.*:ALL,GRANT'
    login_user: 'root'
    login_password: 'sitagile'
    state: present


- name: Reload privilege tables and Restart MariaDB
  command: 'systemctl restart mariadb'
  changed_when: False